# cclint設定ファイルの例
# このファイルを.cclint.yamlとしてプロジェクトルートに配置してください

version: "1.0"

# C++標準バージョン（auto, c++98, c++11, c++14, c++17, c++20, c++23）
cpp_standard: "auto"

# インクルード/除外パターン
include_patterns:
  - "src/**/*.cpp"
  - "src/**/*.hpp"
  - "include/**/*.h"

exclude_patterns:
  - "build/**"
  - "third_party/**"
  - "**/*_test.cpp"

# 出力設定
output_format: "text"  # text, json, xml
max_errors: 0  # 0 = unlimited
show_compiler_output: true

# パフォーマンス設定
num_threads: 0  # 0 = auto-detect
enable_cache: true
cache_directory: ".cclint_cache"

# ルール実行設定
parallel_rules: true
fail_fast: false

# ルール設定
rules:
  # Naming rules
  - name: class-name-camelcase
    enabled: true
    severity: warning
    priority: 50
    parameters:
      allow_underscores: false

  - name: function-name-lowercase
    enabled: true
    severity: warning
    priority: 50
    parameters:
      allow_camelcase: false

  - name: constant-name-uppercase
    enabled: true
    severity: warning
    priority: 50
    parameters:
      apply_to_enum: true

  - name: member-variable-prefix
    enabled: false  # プロジェクトに応じて有効化
    severity: warning
    priority: 50
    parameters:
      prefix: "m_"
      apply_to_static: false

  # Style rules
  - name: braces-on-new-line
    enabled: true
    severity: warning
    priority: 40
    parameters:
      style: "k&r"  # "k&r" or "allman"

  - name: indent-width
    enabled: true
    severity: warning
    priority: 40
    parameters:
      width: 4
      use_tabs: false

  # Structure rules
  - name: one-class-per-file
    enabled: true
    severity: warning
    priority: 30
    parameters:
      allow_nested: true
      allow_private: true

  # Spacing rules
  - name: max-consecutive-empty-lines
    enabled: true
    severity: warning
    priority: 20
    parameters:
      max_lines: 1

  # Documentation rules
  - name: require-function-comments
    enabled: false  # プロジェクトに応じて有効化
    severity: info
    priority: 10
    parameters:
      require_private: false
      min_lines: 5

  # Modernize rules
  - name: use-nullptr
    enabled: true
    severity: warning
    priority: 60
    parameters:
      min_cpp_standard: "c++11"

  - name: use-auto
    enabled: true
    severity: info
    priority: 60

  - name: use-override
    enabled: true
    severity: warning
    priority: 60
    parameters:
      require_virtual_removal: true

  # Performance rules
  - name: pass-by-const-reference
    enabled: true
    severity: warning
    priority: 70
    parameters:
      min_size_bytes: 16
      ignore_trivial: false

  - name: avoid-unnecessary-copy
    enabled: true
    severity: warning
    priority: 70

  # Readability rules
  - name: max-function-length
    enabled: true
    severity: warning
    priority: 50
    parameters:
      max_lines: 50
      count_comments: false
      count_empty_lines: false

  - name: no-magic-numbers
    enabled: true
    severity: warning
    priority: 50
    parameters:
      ignored_values: [0, 1, -1]
      allow_in_tests: true

  # Security rules
  - name: no-unsafe-functions
    enabled: true
    severity: error
    priority: 100

  - name: check-array-bounds
    enabled: true
    severity: error
    priority: 100

lua_scripts:
  - path: scripts/naming/method_naming_by_access.lua
    priority: 80
    parameters:
      custom_param: value
