# cclint設定ファイルの例
# このファイルを.cclint.yamlとしてプロジェクトルートに配置してください

version: "1.0"

# C++標準バージョン（auto, c++98, c++11, c++14, c++17, c++20, c++23）
cpp_standard: "auto"

# インクルード/除外パターン
include_patterns:
  - "*.cpp"
  - "*.hpp"
  - "*.h"
  - "src/**/*.cpp"
  - "src/**/*.hpp"
  - "include/**/*.h"

exclude_patterns:
  - "build/**"
  - "third_party/**"
  - "**/*_test.cpp"

# 出力設定
output_format: "text"  # text, json, xml
max_errors: 0  # 0 = unlimited
show_compiler_output: true

# パフォーマンス設定
num_threads: 0  # 0 = auto-detect
enable_cache: true
cache_directory: ".cclint_cache"

# ルール実行設定
parallel_rules: true
fail_fast: false

# ルール設定
rules:
  # Naming rules
  - name: class-name-camelcase
    enabled: false
    severity: warning
    priority: 50
    parameters:
      allow_underscores: false

lua_scripts:
  - path: ../scripts/rules/naming/method_naming_by_access.lua
    priority: 80
    parameters:
      custom_param: value
